### ISSUE TITLE
Add package to conda-forge

### ISSUE THREAD

**Issue by jrbourbeau** [milesgranger/gilknocker#13]
It'd be great if I could install `gilknocker` from with conda from conda-forge

**Comment by jrbourbeau** [comment]
@milesgranger is this a process you're familiar with? I'm happy to chat if that'd be useful

**Comment by milesgranger** [comment]
Only experience thru [cramjam-feedstock](https://github.com/conda-forge/cramjam-feedstock) for [cramjam](https://github.com/milesgranger/pyrus-cramjam). Although, as you'll see there, the entire build system is replicated for all platforms. I say replicated, because all platforms are built already for wheels on PyPI. Since both that project, and gilknocker don't have any python dependencies, it would be nice if the 'recipe' for the feedstock could be basically "pip install gilknocker".

**Comment by milesgranger** [comment]
Closed by https://github.com/conda-forge/staged-recipes/pull/22311
